"""empty message

Revision ID: 09af32916eca
Revises: 4f6d88729cfa
Create Date: 2019-02-23 18:12:17.224587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09af32916eca'
down_revision = '4f6d88729cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debits', sa.Column('value', sa.Float(), nullable=True))
    op.drop_column('debits', 'valeu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debits', sa.Column('value', sa.FLOAT(), nullable=True))
    op.drop_column('debits', 'value')
    # ### end Alembic commands ###
